chef/urls.py
from django.contrib import admin
from django.urls import path, include
from chef import views

app_name = 'chef'

urlpatterns = [
	path('admin/', admin.site.urls),
	path('chef/', views.chef, name='chef'),
	path('chef/request/', views.bahan, name='bahan'),
	path('list/bahan/', views.list_bahan, name='list_bahan'),
	path('list/bahan/done/<int:id>/', views.req_done, name='req_done'),
	path('getPesanan/', views.getPesanan, name='getPesanan'),
	]

groupProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('chef.urls')),
    path('', include('homepagee.urls')),
    path('', include('kurir.urls'))
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('order/', views.person_create, name="person"),
    path('getData/', views.getData, name="get-data"),
    path('login/', views.login1, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout1, name="logout"),
]

homepagee/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'homepagee'

urlpatterns = [
    path('show/', views.post_list, name='post_list'),
    
    path('bayar/', views.post_new, name='bayar'),
    path('feedback/', views.feedback, name='feedback'),
    path('getDataFeedback/', views.getDataFeedback, name='getDataFeedback'),
    
    url(r'show/(?P<pk>[0-9]+)/delete/$', views.Delete.as_view(),name='delete'),
]

kurir/urls.py
from django.contrib import admin
from django.urls import path, include
from kurir import views

app_name = 'kurir'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kurir/', views.kurir, name='kurir'),
  ]

homepage/models.py
from django.db import models
import django.utils.timezone


# Create your models here.
class Person1(models.Model):

    name = models.CharField(max_length=100, null=True, blank=True)
    number = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
   
    date = models.DateField(auto_now_add = False, default = django.utils.timezone.now)

    BASE = [
        ('Choco', 'Choco'),
        ('Mix', 'Mix'),
        ('Original', 'Original')
    ]

    donut_base = models.CharField(choices=BASE, default='Original', max_length=10)

    donut_flav_A = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_B = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_C = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_D = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_E = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_F = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_G = models.DecimalField(default=0, max_digits=2, decimal_places=0)
    donut_flav_H = models.DecimalField(default=0, max_digits=2, decimal_places=0)

    def __str__(self):
        return self.name

# class Person1(models.Model):

    # name = models.CharField(max_length=100)
    # number = models.DecimalField(max_digits=100, decimal_places=0)
    # address = models.CharField(max_length=100)
   
    # date = models.DateField(auto_now_add = False, default = django.utils.timezone.now)
    # day = models.CharField(max_length=10, default=None, null=True)
    # time = models.TimeField(auto_now_add = False, default = django.utils.timezone.now)

    # BASE = [
    #     ('Choco', 'Choco'),
    #     ('Mix', 'Mix'),
    #     ('Original', 'Original')
    # ]

    # donut_base = models.CharField(choices=BASE, default='Original', max_length=10)
    
    # donut_flav_A = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_B = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_C = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_D = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_E = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_F = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_G = models.DecimalField(max_digits=2, decimal_places=0)
    # donut_flav_H = models.DecimalField(max_digits=2, decimal_places=0)

    # def __str__(self):
    #     return self.title

homepagee/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    nama=models.CharField(max_length=30, default="")
    feedback= models.CharField(max_length=200)
    
    
    

    def __str__(self):
        return self.nama
        
   

homepagee/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['feedback']
        
        
        
    def __init__(self, *args, **kwargs):
        super(PostForm,self).__init__(*args,**kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        

homepagee/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from homepage.models import Person1
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from homepagee.forms import PostForm
from homepagee.models import Post
from django.core import serializers
# Create your views here.
def post_list(request):
    return render(request, 'post_list.html', {'postlist': Person1.objects.all()})
    
def feedback(request):
    postlist = Post.objects.all()
    return render(request, 'feedback.html', {'postlist2':postlist, 'postlist3' : Person1.objects.all()})
    
    
def post_new(request):
    if request.method == "POST":
           form = PostForm(request.POST)
           if form.is_valid():
               post = form.save(commit=False)
               post.nama=request.user
               post.save()
               return redirect('/feedback/')
    else:
        form = PostForm()
    return render(request, 'bayar.html', {'form': form})
    
    
class Delete(DeleteView):
    model=Person1
    success_url=reverse_lazy('homepagee:post_list')
    
def getDataFeedback(request):
    feedback=Post.objects.all()
    feedback_list=serializers.serialize('json', feedback)
    return HttpResponse(feedback_list, content_type="text/json-comment-filtered")
    

homepagee/templates/bayar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<html>
<head>
	<title>Ringkasan</title>
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" >
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="{% static 'js/feedback.js'  %}"></script>
	<script src="{% static 'js/jquery-3.4.1.min.js'  %}"></script>
	
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script>
	$(document).ready(function(){
	  $("#act").click(function(){
	    $("#rek").toggle("slow");
	  });
	});
	</script>
</head>
 <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F8BBD0;">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Donat</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Beranda</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chef:chef' %}">Koki</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chef:list_bahan' %}">Bahan Pesanan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'kurir:kurir' %}">Kurir</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:logout'%}">Logout</a>
            </li>
            {% elif user.is_authenticated %}
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:person' %}">Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:logout'%}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:login'%}">Login</a>
            </li>
            {% endif %}
            </ul>
        </div>
    </nav>
	<body>
		<style>
		.btq{
			background:#FFAAA5;
		}
		.bg{
			background-color:#F5AB40;
		}
		.a{
			color:#FF8B20;
			text-align:center;
		}
		.space{
			margin:5%;
		}
		.warna{
			color:#DD7777;
			font-size:25px;
		}
		#i{
			left:0px;
			bottom:0px;
		}
		.k{
			margin:3px;
		}
		#act:hover{
			background:#FFAAA5;
			border:#F5AB40;;
		}
		</style>
		
		<div class="k">
	<img src="{% static 'lg.png' %}" width="100px">
</div>	
		
		<h1 class="a space"> Silahkan selesaikan pesanan anda  </h1>
		<div class="space warna">
		<p><br><button class="button-aktivitas buttonku btn btn-outline-secondary" id='act'>Transfer ke salah satu rekening di  bawah ini:</button>
<div id="rek">BNI 029829812<br>
BCA 012836239<br>
Mandiri 1349234630
</div>
<br>
<br>
<br>
<br>
Terimakasih telah memilih produk kami. 
Pesanan anda akan segera kami proses
		<br><br></p></div>
		<div class="container">
			<div class="row">
			<div class="col-xl-6">
	    <form method="POST" class="post-form" id="myform">{% csrf_token %}
	        {{ form.as_p }}
			<div class="isi"></div>
	        <button id="but"  class="label label-default h3 save btn btn-default btq">Save</button>
			<br><br>
	    </form>
		
	</div>
	<div class="col" id=i>
		<img id="b" src="{% static 'y.png' %}" width="500px">
	</div>
</div>
</div>

	</body>
	
</html>

homepagee/templates/feedback.html
<DOCTYPE! html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<html>
<head>
	<title>Ringkasan</title>
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" >
	<script src="http://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="{% static 'js/feedback.js'  %}"></script>
	<script src="{% static 'js/jquery-3.4.1.min.js'  %}"></script>
	
	
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
 <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F8BBD0;">
        <a class="navbar-brand" href="{% url 'homepage:home' %}">Donat</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Beranda</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chef:chef' %}">Koki</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'chef:list_bahan' %}">Bahan Pesanan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'kurir:kurir' %}">Kurir</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:logout'%}">Logout</a>
            </li>
            {% elif user.is_authenticated %}
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:person' %}">Pesan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:logout'%}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepagee:feedback' %}">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:login'%}">Login</a>
            </li>
            {% endif %}
            </ul>
        </div>
    </nav>
<body>
	<style>
		.btq{
			background:#FFAAA5;
		}
		.bg{
			background-color:#F5AB40;
		}
		.a{
			color:#FF8B20;
			text-align:center;
		}
		.post{
			display: flex;
			justify-content: center;
			align-items: center;
		}

		.row-striped:nth-of-type(odd){
		  background-color: #FFAAA5;
		  border-left: 4px #000000 solid;
		}

		.row-striped:nth-of-type(even){
		  background-color: #F3A67B;
		  border-left: 4px #efefef solid;
		}

		.row-striped {
		    padding: 15px;
		}
		.k{
			margin:3px;
		}
		#jumlahFeedback{
			margin:30px;
			text-align:center;
			color:#FF8B20;
			
		}
		</style>
		<script>
			$(document).ready(() => {
				console.log(1);
				panggil();
				
			})
				function panggil(){
					console.log(0);
					$.ajax({
						method:'GET',
						url: `/getDataFeedback/`,
						success: function(feedback){
							console.log(1);
							console.log(feedback.length);
							$("#jumlahFeedback").empty();
							$("#jumlahFeedback").append("<p>Total feedback: " + feedback.length +"<p>")
						}
						
					})
				}
	
			</script>
		<div class="k">
	<a href="{% url 'homepage:home' %}"><img src="{% static 'lg.png' %}" width="100px"></a>
</div>
	<br><br>
	<h1 class="a"> Feedback </h1>
	<div id="jumlahFeedback"> jumlah</div>
	
	<div class="show post container">
		<div class= "col-xl-6">
		<br><br><br><br>
		{% for post in postlist2 %}
			<div class="row row-striped">
				<p id="id_name"><strong>{{ post.nama }}</strong><br>
				{{post.feedback}} </p>
				
					</div>				
				
					{% endfor %}
					
		<br><br>
	</div>
		
			
					
					
				
			   	


</html>

homepagee/templates/post_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<html>
<head>
	<title>Ringkasan</title>
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
	<link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" >
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	<script src="{% static 'js/feedback.js'  %}"></script>
	<script src="{% static 'js/jquery-3.4.1.min.js'  %}"></script>
	
	<link href="https://fonts.googleapis.com/css?family=Chilanka&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	
</head>
<body>
	<style>
		
		.btq{
			background:#FFAAA5;
		}
		.bg{
			background-color:#F5AB40;
		}
		.a{
			color:#FF8B20;
			text-align:center;
		}
		.space{
			margin:5%;
		}
		.post{
			display: flex;
			justify-content: center;
			align-items: center;
		}

		.row-striped:nth-of-type(odd){
		  background-color: white;
		  border: 2px #FFAAA5 solid;
		}

		.row-striped:nth-of-type(even){
		  background-color: white;
		  border: 2px #FFAAA5 solid;
		}

		.row-striped {
		    padding: 15px 0;
		}
		.gambar1{
			width:300px;
		}
		#nol{
			padding:0px;
			margin:0px;
		}
		#hitam{
			color:black;
		}
		.dikit{
			margin:10%;
		}
		.left{
			margin-left:15%;
		}
		.k{
			margin:3px;
		}
		#gambar{
			bottom:20px;
		}
		</style>
		<div class="k">
	<img src="{% static 'lg.png' %}" width="100px">
</div>
	
	<h1 class="a"> Ringkasan order </h1>
	<br>
	
	<div class="show post container" id="orderan">
		<div class= "col-xl-8">
		<br>
		{% for post in postlist %}
			{% if user.username == post.name %}
			<div class="row row-striped" id="jq">
				<div class="container">
				<div class="row">
						<div class="col-2 text-right">
							<h1 class="display-4"><span class="badge badge-secondary">{{ post.deftanggal }}</span></h1>
							<h2>{{ post.bulan }}</h2>
						</div>
						<div class="col">
							<div class="text-uppercase"><strong>{{ post.name }}</strong></div>
							<p>{{ post.number }}</p>
							<p>{{ post.address }}</p>
							
							
						</div>
						<div class="col" id="nol">
							{% if post.donut_flav_A != 0 %}
								<p> Donat A : {{post.donut_flav_A}} pcs</p>
							{% endif %}

							{% if post.donut_flav_B != 0 %}
								<p> Donat B : {{post.donut_flav_B}} pcs</p>
							{% endif %}

							   {% if post.donut_flav_C != 0 %}
								<p> Donat C : {{post.donut_flav_C}} pcs</p>
							{% endif %}
							
							{% if post.donut_flav_D != 0 %}
								<p> Donat D : {{post.donut_flav_D}} pcs</p>
							{% endif %}

							{% if post.donut_flav_E != 0 %}
								<p> Donat E : {{post.donut_flav_E}} pcs</p>
							{% endif %}

							{% if post.donut_flav_F != 0 %}
								<p> Donat F : {{post.donut_flav_F}} pcs</p>
							{% endif %}

							{% if post.donut_flav_G != 0 %}
								<p> Donat G : {{post.donut_flav_G}} pcs</p>
							{% endif %}

							{% if post.donut_flav_H != 0 %}
								<p> Donat H : {{post.donut_flav_H}} pcs</p>
							{% endif %}

						</div>
					</div>
				</div>
					</div>
					<form action="{% url 'homepagee:delete' post.id %}" method="post">
						{% csrf_token %}
					    <input type="hidden" name="post_id" value="{{ post.id }}"/>
					        <button type="" id="hitam" class="btn btn-outline-warning " style="margin-left: 30%;" >
							
					         Hapus
					        </button> 
					</form>
					{% endif %}
					{% endfor %}
					</div>
				</div>
		<br>
					  <div class="dikit">
					    <div class="row">
					      <div class="col-sm-4 left" >
					        <img id="gambar" src="{% static 'd.png' %}"  class="gambar1" style="left:30px;">
					      </div>
					      <div class="col-sm-4">
							<div clas="dikit">
												   	    <div class="row">
			   	      
												   	      <div class="col bg">
												   	        <br><br><h3> <span class="label label-default h3 ">Apakah orderan anda sudah benar?<br><br>
									<div class="container">
									  <div class="row">
									    <div class="col">
									      <a href="{% url 'homepagee:bayar' %}"><button type="button" class="btn btn-outline-secondary btq" >Yes</button>
									    </div>
									    <div class="col">
									      <a href="{% url 'homepage:person' %}"><button type="button" class="btn btn-outline-secondary btq"bg>No</button></a>
									    </div>
									  </div>
								  </span></h3><br>
							  </div>
							</div>
							</div>
							</div>
    
	
							</div>
					      </div>
					    </div> 	
						
	
		
			
					
					
				
			   	

</body>
{% load staticfiles %}
</html>